logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        default:
            format: '%(asctime)s %(levelname)s %(module)s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: default
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class: logging.handlers.TimedRotatingFileHandler
            formatter: default
            level: INFO
            filename: application.log
            encoding: utf-8
            when: MIDNIGHT
            backupCount: 7
    root:
        level: DEBUG
        handlers: [console, file]
database:
    user: postgres
    password: passw0rd
    host: localhost
    port: 5432
    name: python
